name: Publish pattern

on:
  push:
    tags: ["v*"]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Validate
        uses: orkspace/orkestra-action@v1
        with:
          validate: ./katalog.yaml

      - name: Publish to registry
        uses: orkspace/orkestra-action@v1
        with:
          registry-push: "my-operator:${{ github.ref_name }} ."
          registry-url: "ghcr.io/${{ github.repository_owner }}/patterns"
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
