name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate
        uses: orkspace/orkestra-action@v1
        with:
          validate: ./katalog.yaml

      - name: Generate bundle
        uses: orkspace/orkestra-action@v1
        id: bundle
        with:
          generate-bundle: ./katalog.yaml
          generate-bundle-output: bundle.yaml
          generate-bundle-namespace: orkestra-system

      - name: Upload bundle
        uses: actions/upload-artifact@v4
        with:
          name: bundle
          path: ${{ steps.bundle.outputs.bundle-file }}

      - name: E2E
        uses: orkspace/orkestra-action@v1
        with:
          e2e: ./e2e.yaml
