name: Validate Katalog

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Katalog
        id: ork
        uses: orkspace/orkestra-action@v1
        with:
          validate: true

      - name: Print validation log
        run: cat ${{ steps.ork.outputs.validate_log }}
